server:
  port: 7001

spring:
  application:
    ##服务名称
    name: order-service
  cloud:
    nacos:
      discovery:
        ### nacos注册地址
        server-addr: 127.0.0.1:8848
#    loadbalancer:
#      ribbon:
logging:
  level:
    com.wangm.springcloud: debug
#        enabled: false